server:
  port: 10000
spring:
  application:
    name: speal-user
dubbo:
  application:
    name: spearl-user # 服务名
  registry:
    address: zookeeper://127.0.0.1:2181 # 注册中心地址
    parameters[namespace]: spearl
  protocol:
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
    retries: 3 # 重试3次
    delay: -1
  scan:
    base-packages: com.modds.spearl